service: s3-file-upload-project

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-1

custom:
  fileUploadBucketName: ${self:service}-bucket-${self:provider.stage}

plugins:
  - serverless-iam-roles-per-function

functions:
  s3FileUploader:
    handler: src/uploadFile.handler
    name: s3-file-upload-project
    description: This is a lambda function handler that will upload a file to an S3 bucket based on API Gateway trigger
    timeout: 60
    memory_size: 512 
    events:
      - http:
        path: fileUpload
        method: POST
    iamRolesStatements:
      - Effect: Allow
        Action:
        - "s3:Put*"
        Resource: arn:aws:s3:::${self:custom.fileUploadBucketName}/*
    environment:
      FILE_UPLOAD_BUCKET_NAME: ${self:custom.fileUploadBucketName}


resources:
  Resources: 
    FileUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.fileUploadBucketName}
        AccessControl: PublicRead