service: s3-file-upload-project

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-1

custom:
  fileUploadBucketName: ${self:service}-bucket-${self:provider.stage}

resources:
  Resources: 
    FileUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.fileUploadBucketName}
        AccessControl: PublicRead